import {  Manrope,  Noto_Serif } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const Noto = Noto_Serif({
  variable: "--font-notoserif",
  subsets: ["latin"],
});




// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` h-full antialiased`}
    >
      <body className={` ${manrope.className} min-h-full flex flex-col`}>{children}    <Toaster /> </body>
    </html>
  );
}
